export const organizations = [
  {
    id: "org-bts",
    name: "BTS Risk Advisors",
    tenantType: "Agency",
  },
  {
    id: "org-peak",
    name: "Peak Wholesale Partners",
    tenantType: "Wholesaler",
  },
] as const;

export const policies = [
  {
    id: "pol-worlds-apart",
    tenant_id: "org-bts",
    customer_nm: "Worlds Apart Apartments LLC",
    policy_no: "MOS-WA-240701",
    policy_state: "TX",
    effective_dt: "2026-08-01",
    term_dt: "2027-08-01",
    current_carrier: "MiddleOak Specialties",
    product: "Worlds Apart",
    class_of_business: "Apartments",
    line_of_business: "Habitational Package",
    year_built: 1994,
    construction_type: "Joisted Masonry",
    location_limit: 8750000,
    building_limit: 2150000,
    buildings_per_location: 6,
    brokerCode: "TX-1842",
    brokerControlsBusiness: "Yes",
    brokerName: "BTS Risk Advisors",
    dateBindableQuoteNeeded: "2026-07-15",
    targetPremium: 148500,
    useClasses: ["Apartments", "Senior"],
    totalUnits: 184,
    occupiedUnits: 176,
    underConstructionUnits: 0,
    vacantUnits: 8,
    evictedLast12Months: 3,
    prequalificationClear: true,
    ratingItems: {
      ingroundPools: 1,
      centralStationFireAlarms: true,
      hardWiredSmokeDetectors: true,
      sprinkler13R: false,
      commercialGradeSprinkler13: false,
      dogRecreationArea: true,
      stoveTopFireStops: true,
      smokeFreeProperty: false,
      designatedSmokeFreeArea: true,
      gutRehab: false,
      vacantLand: false,
    },
    priorLosses: "No",
    priorLossDescription: "",
  },
  {
    id: "pol-cedar-ridge",
    tenant_id: "org-bts",
    customer_nm: "Cedar Ridge Apartments LLC",
    policy_no: "MGA-GL-104892",
    policy_state: "CO",
    effective_dt: "2025-09-01",
    term_dt: "2026-09-01",
    current_carrier: "Rocky Mountain Specialty",
    product: "Commercial Property",
    class_of_business: "Habitational",
    line_of_business: "Commercial Property",
    year_built: 1998,
    construction_type: "Joisted Masonry",
    location_limit: 6250000,
    building_limit: 1850000,
    buildings_per_location: 4,
  },
  {
    id: "pol-prairie-supply",
    tenant_id: "org-bts",
    customer_nm: "Prairie Supply Warehouse",
    policy_no: "MGA-CP-772014",
    policy_state: "KS",
    effective_dt: "2026-02-15",
    term_dt: "2027-02-15",
    current_carrier: "Summit Excess & Surplus",
    product: "Package",
    class_of_business: "Warehouse",
    line_of_business: "Package",
    year_built: 2008,
    construction_type: "Non-Combustible",
    location_limit: 4800000,
    building_limit: 3200000,
    buildings_per_location: 1,
  },
  {
    id: "pol-lakeside-dining",
    tenant_id: "org-bts",
    customer_nm: "Lakeside Family Dining Inc.",
    policy_no: "MGA-BOP-381245",
    policy_state: "MI",
    effective_dt: "2025-11-30",
    term_dt: "2026-11-30",
    current_carrier: "Great Lakes Mutual",
    product: "Business Owners",
    class_of_business: "Restaurant",
    line_of_business: "Business Owners",
    year_built: 1987,
    construction_type: "Frame",
    location_limit: 2100000,
    building_limit: 950000,
    buildings_per_location: 1,
  },
  {
    id: "pol-mesa-equipment",
    tenant_id: "org-bts",
    customer_nm: "Mesa Equipment Rental",
    policy_no: "MGA-IM-629401",
    policy_state: "AZ",
    effective_dt: "2026-01-01",
    term_dt: "2027-01-01",
    current_carrier: "Desert Star Insurance",
    product: "Inland Marine",
    class_of_business: "Equipment Rental",
    line_of_business: "Inland Marine",
    year_built: 2015,
    construction_type: "Metal",
    location_limit: 3500000,
    building_limit: 1250000,
    buildings_per_location: 2,
  },
  {
    id: "pol-harborview",
    tenant_id: "org-peak",
    customer_nm: "Harborview Medical Plaza",
    policy_no: "MGA-PR-510266",
    policy_state: "FL",
    effective_dt: "2025-08-10",
    term_dt: "2026-08-10",
    current_carrier: "Atlantic Specialty",
    product: "Commercial Property",
    class_of_business: "Medical Office",
    line_of_business: "Commercial Property",
    year_built: 2001,
    construction_type: "Masonry Non-Combustible",
    location_limit: 12250000,
    building_limit: 7900000,
    buildings_per_location: 1,
  },
];

export const carriers = [
  {
    id: "carrier-guard",
    tenant_id: "org-bts",
    carrier: "Berkshire Hathaway GUARD",
    appetite: "Strong",
    states: ["TX", "CO", "KS", "MI"],
    classes: ["Apartments", "Habitational", "Warehouse", "Restaurant"],
    maxLocationLimit: 10000000,
    documents: ["Commercial Property Appetite Guide", "Habitational Supplemental Notes"],
    rationale:
      "Broad commercial property appetite with capacity for established habitational, office, and light commercial schedules.",
  },
  {
    id: "carrier-amtrust",
    tenant_id: "org-bts",
    carrier: "AmTrust E&S",
    appetite: "Moderate",
    states: ["TX", "AZ", "CO", "KS"],
    classes: ["Apartments", "Habitational", "Equipment Rental", "Warehouse"],
    maxLocationLimit: 7000000,
    documents: ["E&S Property Guide", "Small Commercial Eligibility Matrix"],
    rationale:
      "Often competitive for small to middle-market commercial risks where construction and limits are well documented.",
  },
  {
    id: "carrier-crum",
    tenant_id: "org-bts",
    carrier: "Crum & Forster Specialty",
    appetite: "Selective",
    states: ["TX", "CO", "FL", "AZ"],
    classes: ["Apartments", "Habitational", "Medical Office"],
    maxLocationLimit: 15000000,
    documents: ["Specialty Property Appetite Bulletin"],
    rationale:
      "Useful market for excess and specialty property placements requiring underwriting flexibility.",
  },
  {
    id: "carrier-nationwide",
    tenant_id: "org-bts",
    carrier: "Nationwide E&S/Specialty",
    appetite: "Moderate",
    states: ["TX", "MI", "KS", "AZ"],
    classes: ["Apartments", "Restaurant", "Warehouse", "Equipment Rental"],
    maxLocationLimit: 9000000,
    documents: ["Package Appetite Overview", "Property Capacity Desk Reference"],
    rationale:
      "May fit package or property-driven accounts depending on occupancy, location catastrophe exposure, and loss history.",
  },
  {
    id: "carrier-atlantic",
    tenant_id: "org-peak",
    carrier: "Atlantic Specialty",
    appetite: "Strong",
    states: ["FL", "GA", "SC"],
    classes: ["Medical Office", "Office"],
    maxLocationLimit: 20000000,
    documents: ["Coastal Property Appetite Guide"],
    rationale:
      "Configured for the selected tenant and included to demonstrate tenant-isolated carrier intelligence.",
  },
];

export const policyInsightConfigs = {
  "MiddleOak Specialties|Worlds Apart": {
    title: "MiddleOak Specialties Worlds Apart",
    subtitle: "Supplement-driven underwriting checklist",
    requiredAttachments: [
      "ACORD Application",
      "Statement of Values",
      "Completed WORLDS APART Supplement",
      "Currently Valued, 5-Year Hard Copy Loss Runs",
    ],
    sections: [
      {
        title: "Submission Details",
        fields: [
          { label: "Broker Code", key: "brokerCode" },
          { label: "Broker Controls Business", key: "brokerControlsBusiness" },
          { label: "Name of Broker", key: "brokerName" },
          { label: "Date Bindable Quote Needed", key: "dateBindableQuoteNeeded", format: "date" },
          { label: "Target Premium", key: "targetPremium", format: "currency" },
        ],
      },
      {
        title: "Use Classes",
        fields: [
          { label: "Selected Classes", key: "useClasses", format: "list" },
          { label: "Total Number of Units", key: "totalUnits" },
          { label: "Occupied", key: "occupiedUnits" },
          { label: "Under Construction", key: "underConstructionUnits" },
          { label: "Vacant", key: "vacantUnits" },
          { label: "Evicted Last 12 Months", key: "evictedLast12Months" },
        ],
      },
      {
        title: "Rating Items",
        fields: [
          { label: "Number of Inground Pools", key: "ratingItems.ingroundPools" },
          { label: "Central Station Fire Alarms", key: "ratingItems.centralStationFireAlarms", format: "yesNo" },
          { label: "Hard Wired Smoke Detectors", key: "ratingItems.hardWiredSmokeDetectors", format: "yesNo" },
          { label: "Full System 13R Sprinkler", key: "ratingItems.sprinkler13R", format: "yesNo" },
          { label: "Commercial Grade Sprinkler", key: "ratingItems.commercialGradeSprinkler13", format: "yesNo" },
          { label: "Dog Recreation Area", key: "ratingItems.dogRecreationArea", format: "yesNo" },
          { label: "Stove Top Fire Stops", key: "ratingItems.stoveTopFireStops", format: "yesNo" },
          { label: "Smoke Free Property", key: "ratingItems.smokeFreeProperty", format: "yesNo" },
          { label: "Designated Smoke Free Area", key: "ratingItems.designatedSmokeFreeArea", format: "yesNo" },
          { label: "Gut Rehab", key: "ratingItems.gutRehab", format: "yesNo" },
          { label: "Vacant Land", key: "ratingItems.vacantLand", format: "yesNo" },
        ],
      },
    ],
    knockoutItems: [
      "Locations undergoing major construction",
      "Armed guards, courtesy officers, or off-duty police officers",
      "Major systems not updated within the past 30 years",
      "Disqualifying electrical conditions",
      "Galvanized or polybutylene piping",
    ],
  },
} as const;
